Remove redundant info
aeternity/ae-channel-service pull request #4
Opened 2019-08-09 13:03 UTC by AleksandarFilipov

Small cleanup - no big deal, no functional changes.

2019-08-09 15:48 UTC, tolbrino requested changes

2019-08-09 15:48 UTC, tolbrino commented on apps/ae_socket_connector/lib/socket_connector.ex
> +  # def start_link(
This code can be removed, right?

2019-08-13 06:55 UTC, AleksandarFilipov commented on apps/ae_socket_connector/lib/socket_connector.ex
> +  # def start_link(
Yep, now been removed.

2019-08-13 08:57 UTC, tolbrino approved these changes

2019-08-13 09:55 UTC, merged